; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
monitor_filters = direct, printable
build_type = release
board_build.partitions = partitions.csv
build_flags = 
	-DCONFIG_BT_ENABLED=1
	-DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=1
	-DCONFIG_BT_BLE_ENABLED=1
	-DUSE_STATUS_LED=1
	-DSTATUS_LED_PIN=4
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	bblanchon/ArduinoJson@^7.0.0
	densaugeo/base64@^1.4.0
	knolleary/PubSubClient@^2.8
	codewitch-honey-crisis/htcw_json@^0.2.5
	adafruit/Adafruit NeoPixel
[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600
build_type = release
board_build.partitions = partitions.csv

build_flags =
    -DUSE_LCD=0
    -DUSE_STATUS_LED=1
    -DSTATUS_LED_PIN=21

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bblanchon/ArduinoJson@^7.0.0
    densaugeo/base64@^1.4.0
    knolleary/PubSubClient@^2.8
    codewitch-honey-crisis/htcw_json@^0.2.5
    adafruit/Adafruit NeoPixel
