; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
monitor_filters = direct, printable
build_type = release
board_build.partitions = partitions.csv
build_flags = 
	-DCONFIG_BT_ENABLED=1
	-DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=1
	-DCONFIG_BT_BLE_ENABLED=1
	-DUSE_LCD=1
	-DUSE_STATUS_LED=1
	-DSTATUS_LED_PIN=4
    -DNFC_PIN_PN5180_RST=13
    -DNFC_PIN_PN5180_NSS=14
    -DNFC_PIN_PN5180_MOSI=27
    -DNFC_PIN_PN5180_MISO=26
    -DNFC_PIN_PN5180_SCK=25
    -DNFC_PIN_PN5180_BUSY=33
    -DNFC_PIN_PN5180_GPIO=32
    -DNFC_PIN_PN5180_IRQ=35
    -DNFC_PIN_PN5180_AUX=34
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	bblanchon/ArduinoJson@^7.0.0
	densaugeo/base64@^1.4.0
	knolleary/PubSubClient@^2.8
	codewitch-honey-crisis/htcw_json@^0.2.5
	adafruit/Adafruit NeoPixel
[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600
monitor_filters = direct, printable
build_type = release
board_build.partitions = partitions.csv

build_flags =
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=1
    -DCONFIG_BT_BLE_ENABLED=1
    -DUSE_LCD=0
    -DUSE_STATUS_LED=1
    -DSTATUS_LED_PIN=21
    -DNFC_PIN_PN5180_RST=4
    -DNFC_PIN_PN5180_NSS=5
    -DNFC_PIN_PN5180_MOSI=6
    -DNFC_PIN_PN5180_MISO=7
    -DNFC_PIN_PN5180_SCK=8
    -DNFC_PIN_PN5180_BUSY=9
    -DNFC_PIN_PN5180_GPIO=10
    -DNFC_PIN_PN5180_IRQ=11
    -DNFC_PIN_PN5180_AUX=12

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bblanchon/ArduinoJson@^7.0.0
    densaugeo/base64@^1.4.0
    knolleary/PubSubClient@^2.8
    codewitch-honey-crisis/htcw_json@^0.2.5
    adafruit/Adafruit NeoPixel
